// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYSy7O9CF2tF-ZVcU44i5mN9lCLvv4wFo',
    appId: '1:299163512241:web:9938344093b6a6bf3ee190',
    messagingSenderId: '299163512241',
    projectId: 'trips-c0544',
    authDomain: 'trips-c0544.firebaseapp.com',
    storageBucket: 'trips-c0544.appspot.com',
    measurementId: 'G-NE08QH789S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-oS5JhAcYIoQbeOavkX4X0dB31gp4bo',
    appId: '1:299163512241:android:3ec895798653e5ec3ee190',
    messagingSenderId: '299163512241',
    projectId: 'trips-c0544',
    storageBucket: 'trips-c0544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLKPOAkaCHP6EJyoZEETbHjr4nPXho2s',
    appId: '1:299163512241:ios:8ce55ccafd56f5353ee190',
    messagingSenderId: '299163512241',
    projectId: 'trips-c0544',
    storageBucket: 'trips-c0544.appspot.com',
    iosClientId: '299163512241-mca4707ibau6bv3c9o2c0kmjoccgedma.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTrips',
  );
}
